@extends('UATWEB.layouts.main')

@section('title')
How do Social Media checks compliment background checks? - Avvanz Global
@endsection

@section('css')
<link rel="preload" href="{{ asset('images/resources/background/itemsBg.webp') }}" as="image">

<style>
    .bg-image-2 {
        background: url("../images/resources/background/itemsBg.webp") no-repeat center;
        background-size: cover;
        position: relative;
        min-height: 100px;
    }

    .bg-image-2::before {
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(18, 71, 95, 0.8);
        z-index: 1;
    }

    .bg-image-2 .container {
        position: relative;
        z-index: 2;
    }
</style>
@endsection

@section('content')

<section class="bg-image-2">
    <div class="container padding-vertical text-white">
        <h1 class="fw-bolder display-5">
            How do Social Media checks compliment background checks?
        </h1>
        <p>
            <i class="fa fa-calendar"></i> June 11, 2021
        </p>
    </div>
</section>

<section class="container margin-vertical">
    <div class="text-center my-3">
        <img class="img-fluid w-50 h-50 transition-up rounded" src="{{ asset('images/resources/blogItems/blog1-1.webp') }}" alt="blog1-1">
    </div> 
    <p>
        In its 2020 Report, the Association of Certified Fraud Examiners estimated that 5% of all revenue generated by companies – some three and half trillion pounds globally – is lost every year through fraud committed by employees. Some of these are mega-frauds involving tens or hundreds of millions, even billions, being misappropriated by CEOs or high-profile businessmen. 
    </p>
    <p>
        Hence its important to do thorough background checks on potential employees to ensure the right hires. 
    </p>
    <p>
        If thorough screening is done before new hires are onboarded, this would lessen the occurrences of such events which costs the companies unnecessary trouble. 
    </p>
    <p class="fw-bolder">
        Consider doing a social media check
    </p>
    <p>
        When recruiting  a new hire, it is highly beneficial for companies to screen the candidate’s social media profile to gain a deeper insight into the candidate’s personality and how they truly behave as the candidate represents your brand. They reveal behavior that may not be in line with the organisation’s values or beliefs. 3 key benefits for companies in conducting social media checks include:
    </p>
    <ul>
        <li>
            Inexpensive way of learning more about and vetting a candidate as interviews are not necessarily foolproof
        </li>
        <li>
            Insights in areas of  sexually explicit content, Potentially unlawful activities, Potentially violent behaviours, Racism and/or Demonstrations of intolerance. 
        </li>
        <li>
            Checking into professional references or recommendations
        </li>
    </ul>
    <p>
        Social Media Checks should compliment a candidate’s background check and not be used on its own. While social media checking provides a dimension to the candidate’s personality which may not be surfaced during the interview or background checks. It doesn’t guarantee full insights to whether the candidate is a good cultural fit to your organization.
    </p>
    <p>
        Instead, it’s a way to see if an applicant is true to themselves and indeed the person they present themselves to be in the interview. Social media screening can help supplement criminal searches and help sieve out candidates with intolerant behaviors that may not be in line with the organization’s values. 
    </p>
    <p>
        Here are some of the benefits of conducting social media checks:
    </p>
    <ul>
        <li>
            You understand your candidates better
        </li>
        <li>
            It’s budget-friendly and saves time
        </li>
    </ul>
    <p>
        What employers can find out about a candidate from social media checks:
    </p>
    <ul>
        <li>
            Culture fit
        </li>
        <li>
            Personality and passions
        </li>
    </ul>
    <p>
        Traditional background checks and due diligence checks on individuals and/or companies uncover historical datapoints of the subjects involved and this is extremely important before engaging the subjects. In a background check, checks would be done on their education background, criminal records, financial and any litigations related to the candidate. 
    </p>
    <p>
        We don’t recommend social media screening to be the only check done on a potential candidate to decide on the hiring. It should be perceived as a valuable data point in addition to other checks. Discriminatory elements relating to gender, sexual orientation, religion, race, disability, and political affiliations should ideally be filtered out.  
    </p>
    <p>
        These kinds of Social Media Checks definitely add value to the background checks as past data along with current dynamic data yields a complete thorough profile of the candidate thus aiding employers in making critical hiring decisions. With more of these checks now being very prevalent, it’s hoped that individuals will exercise more caution and responsibility when commenting, liking, following and even sharing posts on the various social media platforms. As derogatory comments can cause them a potential role. 
    </p>
    <div class="d-flex justify-content-center">
        <section class="mb-4 d-flex">
            <p class="fw-bolder m-1 align-content-center">
                Share this story:
            </p>
            <a
                class="btn text-white btn-floating m-1"
                style="background-color: #3b5998;"
                {{-- href="https://www.facebook.com/sharer.php?u=https://www.avvanz.com/how-do-social-media-checks-compliment-background-checks/" --}}
                href="https://www.facebook.com/sharer/sharer.php?u={{ urlencode(url()->current()) }}"
                target="_blank"
                role="button"
            >
                <i class="fab fa-facebook-f"></i>
            </a>
            <a
                class="btn text-white btn-floating m-1"
                style="background-color: #0082ca;"
                {{-- href="https://www.linkedin.com/uas/login?session_redirect=https%3A%2F%2Fwww.linkedin.com%2FshareArticle%3Fmini%3Dtrue%26url%3Dhttps%3A%2F%2Fwww.avvanz.com%2Fhow-do-social-media-checks-compliment-background-checks%2F%26title%3DHow%2520do%2520Social%2520Media%2520checks%2520compliment%2520background%2520checks%253F%2520-%2520Avvanz%2520Global%26summary%3D%26source%3Dhttps%3A%2F%2Fwww.avvanz.com%2Fhow-do-social-media-checks-compliment-background-checks%2F" --}}
                href="https://www.linkedin.com/shareArticle?url={{ urlencode(url()->current()) }}"
                target="_blank"
                role="button"
            >
                <i class="fab fa-linkedin-in"></i>
            </a>
        </section>
    </div>
    <div class="hstack gap-3 text-marigold">
        <div class="vr" style="width: 3px;"></div>
        <h1>
            Latest Blog
        </h1>
    </div>
</section>

@endsection